package com.example.notesminiapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a Note entity in the Room database.
 * Each instance of this class corresponds to a row in the "notes" table.
 *
 * @property id The unique ID of the note. It is auto-generated by Room.
 * @property title The title of the note.
 * @property content The main text content of the note.
 * @property timestamp The time the note was created or last updated, defaults to current time.
 * @property isCompleted A flag indicating if the note is marked as completed.
 */
@Entity(tableName = "notes")
data class Note(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val isCompleted: Boolean = false
)
